name: my_first_app
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  cloud_firestore: ^4.8.4
  dartz: ^0.10.1
  firebase_auth: ^4.7.2
  flutter:
    sdk: flutter
  freezed: ^2.4.1
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  stacked: ^3.4.1+1
  stacked_services: ^1.1.0
  google_sign_in: ^6.1.4
  get_it: ^7.6.0
  firebase_core: ^2.15.1
  relative_time: ^4.0.1
  google_fonts: ^5.1.0
  flutter_local_notifications: ^16.3.2
  flutter_timezone: ^1.0.8
  rxdart: ^0.27.7
  firebase_messaging: ^14.8.0
  http: ^1.2.0
  app_settings: ^5.1.1
  connectivity_plus: ^5.0.2
  google_maps_flutter: ^2.5.3
  geolocator: ^11.0.0
  image_picker: ^1.0.7
  firebase_storage: ^11.6.6
  shared_preferences: ^2.2.2
  firebase_core_web: ^2.12.0
  cloud_firestore_web: ^3.10.6
  location: ^5.0.3
  vibration: ^1.8.4
  cupertino_icons: ^1.0.2
  camera: ^0.10.5+9
  url_launcher: ^6.2.5

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  json_serializable: ^6.7.1
  stacked_generator: ^1.5.0

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/
    - themes/
  